server:
  port: 5003

spring:
  application:
    name: booking

  datasource:
    url: "jdbc:mysql://localhost:3306/salon_bookingdb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: $7090Ashok
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


  mail:
    host: smtp.gmail.com
    port: 587
    username: gedelashipa.1321@gmail.com
    password: rlxz dggl spmd byfd
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read_only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

razorpay:
  api:
    key: "YOUR_KEY"
    secret: "YOUR_KEY_SECRET"

stripe:
  api:
    key: "YOUR_TEST_KEY"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Payment Service"
    description: "Payment Service API For Salon Booking System"
    version: "1.0.0"